"""Add PricingRule model

Revision ID: 037923327ba6
Revises: 2d9a0d9cfa00
Create Date: 2025-09-01 15:27:01.924036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '037923327ba6'
down_revision = '2d9a0d9cfa00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_integration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_name', sa.String(length=50), nullable=False),
    sa.Column('site_url', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tracked_keyword',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keyword')
    )
    op.create_table('blog_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(), nullable=True),
    sa.Column('platform_integration_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['platform_integration_id'], ['platform_integration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keyword_rank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('tracked_keyword_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tracked_keyword_id'], ['tracked_keyword.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pricing_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('trend_threshold', sa.Float(), nullable=False),
    sa.Column('price_adjustment_percentage', sa.Float(), nullable=False),
    sa.Column('price_floor', sa.Float(), nullable=True),
    sa.Column('price_ceiling', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pricing_rule')
    op.drop_table('keyword_rank')
    op.drop_table('blog_post')
    op.drop_table('tracked_keyword')
    op.drop_table('product')
    op.drop_table('platform_integration')
    # ### end Alembic commands ###
