"""Initial migration; create tracked_keyword table

Revision ID: 919dfb5df2bf
Revises:
Create Date: 2025-08-31 22:01:44.587697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '919dfb5df2bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracked_keyword',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keyword')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracked_keyword')
    # ### end Alembic commands ###
