"""Add KeywordRank table

Revision ID: 9d9b78e75622
Revises: 919dfb5df2bf
Create Date: 2025-09-01 05:07:04.748564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d9b78e75622'
down_revision = '919dfb5df2bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracked_keyword',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keyword')
    )
    op.create_table('keyword_rank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('tracked_keyword_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tracked_keyword_id'], ['tracked_keyword.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keyword_rank')
    op.drop_table('tracked_keyword')
    # ### end Alembic commands ###
